package com.ly.bean;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;
@Table(name = "customer")
public class Customer implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_id
     *
     * @mbggenerated
     */
    @Id
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_simple_name
     *
     * @mbggenerated
     */
    private String customerSimpleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_name
     *
     * @mbggenerated
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.owner
     *
     * @mbggenerated
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.telephone
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.mobile_phone
     *
     * @mbggenerated
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.fax
     *
     * @mbggenerated
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.saleman_id
     *
     * @mbggenerated
     */
    private String salemanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_adress
     *
     * @mbggenerated
     */
    private String customerAdress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.delivery_adress
     *
     * @mbggenerated
     */
    private String deliveryAdress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.invoice_adress
     *
     * @mbggenerated
     */
    private String invoiceAdress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.last_deluvery_date
     *
     * @mbggenerated
     */
    private Date lastDeluveryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_id
     *
     * @return the value of customer.customer_id
     *
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_id
     *
     * @param customerId the value for customer.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_simple_name
     *
     * @return the value of customer.customer_simple_name
     *
     * @mbggenerated
     */
    public String getCustomerSimpleName() {
        return customerSimpleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_simple_name
     *
     * @param customerSimpleName the value for customer.customer_simple_name
     *
     * @mbggenerated
     */
    public void setCustomerSimpleName(String customerSimpleName) {
        this.customerSimpleName = customerSimpleName == null ? null : customerSimpleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_name
     *
     * @return the value of customer.customer_name
     *
     * @mbggenerated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_name
     *
     * @param customerName the value for customer.customer_name
     *
     * @mbggenerated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.owner
     *
     * @return the value of customer.owner
     *
     * @mbggenerated
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.owner
     *
     * @param owner the value for customer.owner
     *
     * @mbggenerated
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.title
     *
     * @return the value of customer.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.title
     *
     * @param title the value for customer.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.telephone
     *
     * @return the value of customer.telephone
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.telephone
     *
     * @param telephone the value for customer.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.mobile_phone
     *
     * @return the value of customer.mobile_phone
     *
     * @mbggenerated
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.mobile_phone
     *
     * @param mobilePhone the value for customer.mobile_phone
     *
     * @mbggenerated
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.fax
     *
     * @return the value of customer.fax
     *
     * @mbggenerated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.fax
     *
     * @param fax the value for customer.fax
     *
     * @mbggenerated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.saleman_id
     *
     * @return the value of customer.saleman_id
     *
     * @mbggenerated
     */
    public String getSalemanId() {
        return salemanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.saleman_id
     *
     * @param salemanId the value for customer.saleman_id
     *
     * @mbggenerated
     */
    public void setSalemanId(String salemanId) {
        this.salemanId = salemanId == null ? null : salemanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_adress
     *
     * @return the value of customer.customer_adress
     *
     * @mbggenerated
     */
    public String getCustomerAdress() {
        return customerAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_adress
     *
     * @param customerAdress the value for customer.customer_adress
     *
     * @mbggenerated
     */
    public void setCustomerAdress(String customerAdress) {
        this.customerAdress = customerAdress == null ? null : customerAdress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.delivery_adress
     *
     * @return the value of customer.delivery_adress
     *
     * @mbggenerated
     */
    public String getDeliveryAdress() {
        return deliveryAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.delivery_adress
     *
     * @param deliveryAdress the value for customer.delivery_adress
     *
     * @mbggenerated
     */
    public void setDeliveryAdress(String deliveryAdress) {
        this.deliveryAdress = deliveryAdress == null ? null : deliveryAdress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.invoice_adress
     *
     * @return the value of customer.invoice_adress
     *
     * @mbggenerated
     */
    public String getInvoiceAdress() {
        return invoiceAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.invoice_adress
     *
     * @param invoiceAdress the value for customer.invoice_adress
     *
     * @mbggenerated
     */
    public void setInvoiceAdress(String invoiceAdress) {
        this.invoiceAdress = invoiceAdress == null ? null : invoiceAdress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.last_deluvery_date
     *
     * @return the value of customer.last_deluvery_date
     *
     * @mbggenerated
     */
    public Date getLastDeluveryDate() {
        return lastDeluveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.last_deluvery_date
     *
     * @param lastDeluveryDate the value for customer.last_deluvery_date
     *
     * @mbggenerated
     */
    public void setLastDeluveryDate(Date lastDeluveryDate) {
        this.lastDeluveryDate = lastDeluveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Customer other = (Customer) that;
        return (this.getCustomerId() == null ? other.getCustomerId() == null : this.getCustomerId().equals(other.getCustomerId()))
            && (this.getCustomerSimpleName() == null ? other.getCustomerSimpleName() == null : this.getCustomerSimpleName().equals(other.getCustomerSimpleName()))
            && (this.getCustomerName() == null ? other.getCustomerName() == null : this.getCustomerName().equals(other.getCustomerName()))
            && (this.getOwner() == null ? other.getOwner() == null : this.getOwner().equals(other.getOwner()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getTelephone() == null ? other.getTelephone() == null : this.getTelephone().equals(other.getTelephone()))
            && (this.getMobilePhone() == null ? other.getMobilePhone() == null : this.getMobilePhone().equals(other.getMobilePhone()))
            && (this.getFax() == null ? other.getFax() == null : this.getFax().equals(other.getFax()))
            && (this.getSalemanId() == null ? other.getSalemanId() == null : this.getSalemanId().equals(other.getSalemanId()))
            && (this.getCustomerAdress() == null ? other.getCustomerAdress() == null : this.getCustomerAdress().equals(other.getCustomerAdress()))
            && (this.getDeliveryAdress() == null ? other.getDeliveryAdress() == null : this.getDeliveryAdress().equals(other.getDeliveryAdress()))
            && (this.getInvoiceAdress() == null ? other.getInvoiceAdress() == null : this.getInvoiceAdress().equals(other.getInvoiceAdress()))
            && (this.getLastDeluveryDate() == null ? other.getLastDeluveryDate() == null : this.getLastDeluveryDate().equals(other.getLastDeluveryDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCustomerId() == null) ? 0 : getCustomerId().hashCode());
        result = prime * result + ((getCustomerSimpleName() == null) ? 0 : getCustomerSimpleName().hashCode());
        result = prime * result + ((getCustomerName() == null) ? 0 : getCustomerName().hashCode());
        result = prime * result + ((getOwner() == null) ? 0 : getOwner().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getTelephone() == null) ? 0 : getTelephone().hashCode());
        result = prime * result + ((getMobilePhone() == null) ? 0 : getMobilePhone().hashCode());
        result = prime * result + ((getFax() == null) ? 0 : getFax().hashCode());
        result = prime * result + ((getSalemanId() == null) ? 0 : getSalemanId().hashCode());
        result = prime * result + ((getCustomerAdress() == null) ? 0 : getCustomerAdress().hashCode());
        result = prime * result + ((getDeliveryAdress() == null) ? 0 : getDeliveryAdress().hashCode());
        result = prime * result + ((getInvoiceAdress() == null) ? 0 : getInvoiceAdress().hashCode());
        result = prime * result + ((getLastDeluveryDate() == null) ? 0 : getLastDeluveryDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", customerId=").append(customerId);
        sb.append(", customerSimpleName=").append(customerSimpleName);
        sb.append(", customerName=").append(customerName);
        sb.append(", owner=").append(owner);
        sb.append(", title=").append(title);
        sb.append(", telephone=").append(telephone);
        sb.append(", mobilePhone=").append(mobilePhone);
        sb.append(", fax=").append(fax);
        sb.append(", salemanId=").append(salemanId);
        sb.append(", customerAdress=").append(customerAdress);
        sb.append(", deliveryAdress=").append(deliveryAdress);
        sb.append(", invoiceAdress=").append(invoiceAdress);
        sb.append(", lastDeluveryDate=").append(lastDeluveryDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}