package com.ly.bean;

import com.fasterxml.jackson.annotation.JsonFormat;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;
@Table(name = "delivery_master")
public class DeliveryMaster implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_master.delivery_id
     *
     * @mbggenerated
     */
    @Id
    private Integer deliveryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_master.delivery_property
     *
     * @mbggenerated
     */
    private String deliveryProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_master.delivery_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date deliveryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_master.customer_id
     *
     * @mbggenerated
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_master.sale_man_id
     *
     * @mbggenerated
     */
    private Integer saleManId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_master.delivery_address
     *
     * @mbggenerated
     */
    private String deliveryAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table delivery_master
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_master.delivery_id
     *
     * @return the value of delivery_master.delivery_id
     *
     * @mbggenerated
     */
    public Integer getDeliveryId() {
        return deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_master.delivery_id
     *
     * @param deliveryId the value for delivery_master.delivery_id
     *
     * @mbggenerated
     */
    public void setDeliveryId(Integer deliveryId) {
        this.deliveryId = deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_master.delivery_property
     *
     * @return the value of delivery_master.delivery_property
     *
     * @mbggenerated
     */
    public String getDeliveryProperty() {
        return deliveryProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_master.delivery_property
     *
     * @param deliveryProperty the value for delivery_master.delivery_property
     *
     * @mbggenerated
     */
    public void setDeliveryProperty(String deliveryProperty) {
        this.deliveryProperty = deliveryProperty == null ? null : deliveryProperty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_master.delivery_date
     *
     * @return the value of delivery_master.delivery_date
     *
     * @mbggenerated
     */
    public Date getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_master.delivery_date
     *
     * @param deliveryDate the value for delivery_master.delivery_date
     *
     * @mbggenerated
     */
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_master.customer_id
     *
     * @return the value of delivery_master.customer_id
     *
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_master.customer_id
     *
     * @param customerId the value for delivery_master.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_master.sale_man_id
     *
     * @return the value of delivery_master.sale_man_id
     *
     * @mbggenerated
     */
    public Integer getSaleManId() {
        return saleManId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_master.sale_man_id
     *
     * @param saleManId the value for delivery_master.sale_man_id
     *
     * @mbggenerated
     */
    public void setSaleManId(Integer saleManId) {
        this.saleManId = saleManId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_master.delivery_address
     *
     * @return the value of delivery_master.delivery_address
     *
     * @mbggenerated
     */
    public String getDeliveryAddress() {
        return deliveryAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_master.delivery_address
     *
     * @param deliveryAddress the value for delivery_master.delivery_address
     *
     * @mbggenerated
     */
    public void setDeliveryAddress(String deliveryAddress) {
        this.deliveryAddress = deliveryAddress == null ? null : deliveryAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_master
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DeliveryMaster other = (DeliveryMaster) that;
        return (this.getDeliveryId() == null ? other.getDeliveryId() == null : this.getDeliveryId().equals(other.getDeliveryId()))
            && (this.getDeliveryProperty() == null ? other.getDeliveryProperty() == null : this.getDeliveryProperty().equals(other.getDeliveryProperty()))
            && (this.getDeliveryDate() == null ? other.getDeliveryDate() == null : this.getDeliveryDate().equals(other.getDeliveryDate()))
            && (this.getCustomerId() == null ? other.getCustomerId() == null : this.getCustomerId().equals(other.getCustomerId()))
            && (this.getSaleManId() == null ? other.getSaleManId() == null : this.getSaleManId().equals(other.getSaleManId()))
            && (this.getDeliveryAddress() == null ? other.getDeliveryAddress() == null : this.getDeliveryAddress().equals(other.getDeliveryAddress()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_master
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDeliveryId() == null) ? 0 : getDeliveryId().hashCode());
        result = prime * result + ((getDeliveryProperty() == null) ? 0 : getDeliveryProperty().hashCode());
        result = prime * result + ((getDeliveryDate() == null) ? 0 : getDeliveryDate().hashCode());
        result = prime * result + ((getCustomerId() == null) ? 0 : getCustomerId().hashCode());
        result = prime * result + ((getSaleManId() == null) ? 0 : getSaleManId().hashCode());
        result = prime * result + ((getDeliveryAddress() == null) ? 0 : getDeliveryAddress().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_master
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", deliveryId=").append(deliveryId);
        sb.append(", deliveryProperty=").append(deliveryProperty);
        sb.append(", deliveryDate=").append(deliveryDate);
        sb.append(", customerId=").append(customerId);
        sb.append(", saleManId=").append(saleManId);
        sb.append(", deliveryAddress=").append(deliveryAddress);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}