package com.ly.bean;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
@Table(name = "delivery_detail")
public class DeliveryDetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_detail.id
     *
     * @mbggenerated
     */
    @Id
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_detail.delivery_id
     *
     * @mbggenerated
     */
    private Integer deliveryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_detail.product_id
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_detail.sales_quantity
     *
     * @mbggenerated
     */
    private String salesQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_detail.sales_unit_price
     *
     * @mbggenerated
     */
    private Double salesUnitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_detail.sales_amount
     *
     * @mbggenerated
     */
    private Double salesAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table delivery_detail
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_detail.id
     *
     * @return the value of delivery_detail.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_detail.id
     *
     * @param id the value for delivery_detail.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_detail.delivery_id
     *
     * @return the value of delivery_detail.delivery_id
     *
     * @mbggenerated
     */
    public Integer getDeliveryId() {
        return deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_detail.delivery_id
     *
     * @param deliveryId the value for delivery_detail.delivery_id
     *
     * @mbggenerated
     */
    public void setDeliveryId(Integer deliveryId) {
        this.deliveryId = deliveryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_detail.product_id
     *
     * @return the value of delivery_detail.product_id
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_detail.product_id
     *
     * @param productId the value for delivery_detail.product_id
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_detail.sales_quantity
     *
     * @return the value of delivery_detail.sales_quantity
     *
     * @mbggenerated
     */
    public String getSalesQuantity() {
        return salesQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_detail.sales_quantity
     *
     * @param salesQuantity the value for delivery_detail.sales_quantity
     *
     * @mbggenerated
     */
    public void setSalesQuantity(String salesQuantity) {
        this.salesQuantity = salesQuantity == null ? null : salesQuantity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_detail.sales_unit_price
     *
     * @return the value of delivery_detail.sales_unit_price
     *
     * @mbggenerated
     */
    public Double getSalesUnitPrice() {
        return salesUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_detail.sales_unit_price
     *
     * @param salesUnitPrice the value for delivery_detail.sales_unit_price
     *
     * @mbggenerated
     */
    public void setSalesUnitPrice(Double salesUnitPrice) {
        this.salesUnitPrice = salesUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_detail.sales_amount
     *
     * @return the value of delivery_detail.sales_amount
     *
     * @mbggenerated
     */
    public Double getSalesAmount() {
        return salesAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_detail.sales_amount
     *
     * @param salesAmount the value for delivery_detail.sales_amount
     *
     * @mbggenerated
     */
    public void setSalesAmount(Double salesAmount) {
        this.salesAmount = salesAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_detail
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DeliveryDetail other = (DeliveryDetail) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDeliveryId() == null ? other.getDeliveryId() == null : this.getDeliveryId().equals(other.getDeliveryId()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getSalesQuantity() == null ? other.getSalesQuantity() == null : this.getSalesQuantity().equals(other.getSalesQuantity()))
            && (this.getSalesUnitPrice() == null ? other.getSalesUnitPrice() == null : this.getSalesUnitPrice().equals(other.getSalesUnitPrice()))
            && (this.getSalesAmount() == null ? other.getSalesAmount() == null : this.getSalesAmount().equals(other.getSalesAmount()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_detail
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDeliveryId() == null) ? 0 : getDeliveryId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getSalesQuantity() == null) ? 0 : getSalesQuantity().hashCode());
        result = prime * result + ((getSalesUnitPrice() == null) ? 0 : getSalesUnitPrice().hashCode());
        result = prime * result + ((getSalesAmount() == null) ? 0 : getSalesAmount().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_detail
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", deliveryId=").append(deliveryId);
        sb.append(", productId=").append(productId);
        sb.append(", salesQuantity=").append(salesQuantity);
        sb.append(", salesUnitPrice=").append(salesUnitPrice);
        sb.append(", salesAmount=").append(salesAmount);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}